[tasks.build-wasm]
command = "cargo"
args = ["build", "-p", "*_app_wasm", "--target", "wasm32-unknown-unknown"]
workspace = false

[tasks.build-wasm-release]
command = "cargo"
args = [
    "build",
    "-p",
    "*_app_wasm",
    "--target",
    "wasm32-unknown-unknown",
    "--release",
]
workspace = false

[tasks.build-web]
command = "wasm-bindgen"
args = [
    "--target",
    "deno",
    "--no-typescript",
    "target/wasm32-unknown-unknown/debug/cheese_app_wasm.wasm",
    "--out-dir",
    "wasm",
    "--out-name",
    "cheese",
]
dependencies = ["build-wasm"]
workspace = false

[tasks.build-web-release]
command = "wasm-bindgen"
args = [
    "--target",
    "deno",
    "--no-typescript",
    "target/wasm32-unknown-unknown/release/cheese_app_wasm.wasm",
    "--out-dir",
    "wasm",
    "--out-name",
    "cheese",
]
dependencies = ["build-wasm-release"]
workspace = false

[tasks.build-web-prod]
command = "wasm-opt"
args = ["-Oz", "-o", "wasm/cheese_bg.wasm", "wasm/cheese_bg.wasm"]
dependencies = ["build-web-release"]
workspace = false
